#!/bin/bash


# general functions

function pause(){
  read -p "$*"
}

function welcome(){
  echo -e "Welcome to DA-PersianGulf-skin installer."
}

function bar(){
  echo "========================================"
}

# login functions

function login(){
  cd /usr/local/directadmin/data/templates/
  rm $login
  wget https://raw.githubusercontent.com/nilnvoid/DA-PersianGulf-skin/master/utils/login/login.html
}

# skin functions

function end(){
  bar
  echo "Congratulations!!, DA-PersianGulf-skin was installed"
  bar
  echo "Now go to http://yourdomain:2222 or #PORT# and"
  echo "1 | Join admin account"
  echo "2 | As reseller, go to the skin manager"
  echo "3 | Select DA-PersianGulf-skin and apply to me"
  bar
  echo "Thanks for using DA PersianGulf skin"
  bar
}

function joinFolder(){
  cd /usr/local/directadmin/data/skins/
}

function install(){
  echo "Installing..."
  git clone https://github.com/nilnvoid/DA-PersianGulf-skin.git
  chown -R diradmin:diradmin DA-PersianGulf-skin/
}

function update(){
  echo "Updating..."
  git reset --hard
  git pull
  chown -R diradmin:diradmin *
}

# innit

bar
welcome
bar

joinFolder

directory=DA-PersianGulf-skin
login=./login.html

if [ -d "$directory" ]; then
  echo "The directory DA-PersianGulf-skin already exists"
  echo -e "\x1B[31m == UPDATE == \x1B[0m"
  pause 'If you want update the skin, press [Enter] key for continue...'
  cd $directory/
  update
  # install login template
  login
  
else
  pause 'Press [Enter] key for start installation...'
  install
  end
fi

